name: hello world work flow
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu_latest
    steps:
      - name: hello-world
        run: echo "hello world123..."
        shell: bash
    
